### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by aurock-dev** [aurock-dev/colorle#1]
- [ ] Bouton aide
- [ ] Amélio UI/UX
- [ ] Stocker infos
- [ ] Changelog
- [ ] Liens
- [ ] Domaine
- [ ] Nom de la couleur ? https://shallowsky.com/colormatch/index.php?r=32&g=230&b=190
- [ ] Choix de la date pour la couleur
